# Generated by Django 4.0.4 on 2022-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
