# Generated by Django 4.0.4 on 2022-05-25 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderd_date',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 18, 45, 26, 661226)),
        ),
    ]
